INSERT INTO TRADE.TICKER(TICKER, NAME) VALUES('AUDKRW=X', 'Currency Rate AUD/KRW');
INSERT INTO TRADE.TICKER(TICKER, NAME) VALUES('^KS11', 'KOSPI Composite Index');
INSERT INTO TRADE.TICKER(TICKER, NAME) VALUES('^GSPC', 'S&P500 Index');
INSERT INTO TRADE.TICKER(TICKER, NAME) VALUES('^VIX', 'CBOE Volatility Index');
